### ISSUE TITLE
동적 include

### ISSUE THREAD

**Issue by item4** [item4/worst-php-code#5]
``` php
<?
include "color_setting/$owner.php";
?>
```

IDEA from @marnitto

**Comment by marnitto** [comment]
취약점 재현을 조금 더 쉽게 하려면 아래처럼 코드를 바꾸는 게 좋을 것 같습니다.

``` php
<?php
chdir('color_setting');
include "$owner.php";
```

이렇게 하면, `/?owner=php://filter/read=string.rot13/resource=../config` 으로 `config.php`를 읽을 수 있습니다.
